remote_theme:  allejo/jekyll-docs-theme
name: Overview

license:
  software: GNU License 3.0
  software_url: https://www.gnu.org/licenses/licenses.en.html
 
links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/jianyanglab/dNdS-Fun
  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/jianyanglab/dNdS-Fun
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/jianyanglab/dNdS-Fun
    - title: Issues
      icon: bug
      url: https://github.com/jianyanglab/dNdS-Fun/issues?state=open


ui:
  mode: 'light' # 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#525252"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    light:
      color1: "#483D8B"
      color2: "#7B68EE"
    dark:
      color1: "#080331"
      color2: "#673051"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'center'
      page: 'left'

social:
  github:
    user: jianyanglab
    repo: dNdS-Fun
  twitter:
    enabled: false
    via:
    hash:
    account:
  facebook:
    enabled: false
    profileUrl:

# Build settings
markdown: kramdown
exclude:
  - LICENSE.md
  - README.md
